In [1]:
import torch

In [5]:
# Создайте случайный FloatTensor размера 3x4x5
a = (torch.rand(3,4,5))
print(a)
print(a.type())

tensor([[[0.6467, 0.3305, 0.4221, 0.8886, 0.3460],
         [0.6767, 0.7551, 0.9889, 0.1123, 0.7651],
         [0.3932, 0.2392, 0.3676, 0.7250, 0.7768],
         [0.6453, 0.6801, 0.1030, 0.5747, 0.9115]],

        [[0.7270, 0.5146, 0.8834, 0.8782, 0.0436],
         [0.1941, 0.8088, 0.1331, 0.4488, 0.3151],
         [0.8844, 0.8062, 0.9790, 0.8757, 0.8966],
         [0.0374, 0.1030, 0.8821, 0.4815, 0.3657]],

        [[0.3161, 0.9328, 0.0254, 0.6416, 0.4486],
         [0.4427, 0.1421, 0.2310, 0.9309, 0.4890],
         [0.0991, 0.6759, 0.5781, 0.1385, 0.2462],
         [0.7117, 0.2346, 0.5163, 0.7485, 0.2739]]])
torch.FloatTensor


In [6]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [8]:
# Приведите его к форме 6 X 10
c = torch.reshape(a, [6, 10])
print(c)
c.shape

tensor([[0.6467, 0.3305, 0.4221, 0.8886, 0.3460, 0.6767, 0.7551, 0.9889, 0.1123,
         0.7651],
        [0.3932, 0.2392, 0.3676, 0.7250, 0.7768, 0.6453, 0.6801, 0.1030, 0.5747,
         0.9115],
        [0.7270, 0.5146, 0.8834, 0.8782, 0.0436, 0.1941, 0.8088, 0.1331, 0.4488,
         0.3151],
        [0.8844, 0.8062, 0.9790, 0.8757, 0.8966, 0.0374, 0.1030, 0.8821, 0.4815,
         0.3657],
        [0.3161, 0.9328, 0.0254, 0.6416, 0.4486, 0.4427, 0.1421, 0.2310, 0.9309,
         0.4890],
        [0.0991, 0.6759, 0.5781, 0.1385, 0.2462, 0.7117, 0.2346, 0.5163, 0.7485,
         0.2739]])


torch.Size([6, 10])

In [46]:
# Создайте случайный IntTensor размера 10
b = torch.randperm(10)
print(b)

tensor([6, 5, 3, 9, 2, 4, 1, 8, 0, 7])


In [53]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно
d = c*b
print(d)
print(d.type())

tensor([[3.8802, 1.6527, 1.2664, 7.9975, 0.6920, 2.7067, 0.7551, 7.9115, 0.0000,
         5.3557],
        [2.3591, 1.1958, 1.1027, 6.5248, 1.5536, 2.5811, 0.6801, 0.8237, 0.0000,
         6.3806],
        [4.3619, 2.5729, 2.6501, 7.9042, 0.0872, 0.7762, 0.8088, 1.0645, 0.0000,
         2.2056],
        [5.3064, 4.0309, 2.9371, 7.8810, 1.7932, 0.1495, 0.1030, 7.0565, 0.0000,
         2.5602],
        [1.8965, 4.6640, 0.0761, 5.7746, 0.8972, 1.7709, 0.1421, 1.8477, 0.0000,
         3.4233],
        [0.5947, 3.3797, 1.7344, 1.2461, 0.4924, 2.8470, 0.2346, 4.1300, 0.0000,
         1.9175]])
torch.FloatTensor


In [55]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
e = d.matmul(d.T)
print(e)

tensor([[183.0012, 113.9726, 110.7531, 165.2621,  99.8193,  71.2231],
        [113.9726, 101.7127,  85.5012,  97.3895,  77.2394,  39.3972],
        [110.7531,  85.5012, 102.4068, 117.1077,  77.2026,  36.8037],
        [165.2621,  97.3895, 117.1077, 174.7409,  98.2881,  67.0793],
        [ 99.8193,  77.2394,  77.2026,  98.2881,  77.7959,  43.9306],
        [ 71.2231,  39.3972,  36.8037,  67.0793,  43.9306,  45.4734]])


In [56]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.autograd.Variable(torch.FloatTensor([1]),   requires_grad = True)
z = torch.autograd.Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = torch.autograd.Variable(torch.FloatTensor([2]),   requires_grad = True)

y = x**3 + z -75*t

y.backward()

(x.grad, z.grad, t.grad)

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [57]:
# Создайте единичный тензор размера 5x6
f = torch.ones(5,6)
print(f)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [59]:
# Переведите его в формат numpy
g = f.numpy()
print(g)
print(type(g))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
